[project]
name = "solid-execute-buffer"
authors = ["Solid Execute Team"]
description = "A robust smart contract for executing and managing computational buffers"
telemetry = false
requirements = []
[contracts.execute-buffer]
path = "contracts/execute-buffer.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
